# Generated by Django 4.2.30 on 2026-05-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.FloatField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('agilidad', models.FloatField()),
                ('fuerza', models.FloatField()),
                ('potencia', models.FloatField()),
                ('partidos_jugados', models.FloatField()),
                ('puntos_anotados', models.FloatField()),
                ('partidos_ganados', models.FloatField()),
                ('entrenado', models.BooleanField(default=False)),
                ('pca_x', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
