# Generated by Django 4.2.30 on 2026-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='pca_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
